### ISSUE TITLE
Database Secret in Browser?

### ISSUE THREAD

**Issue by EisenbergEffect** [fauna/faunadb-js-release#13]
FaunaDB looks fascinating and in many ways is exactly what I've been looking for, for a long time. However, I'm a bit concerned about putting the database secret into source that's running in a browser. It seems like that would give someone full access to the database. Does the browser client restrict certain operations that the server client doesn't? Or does this assume that you've preconfigured the database in such a way to lock things down such that no client can perform operations you don't allow, regardless of who has the key?

**Comment by jchris** [comment]
Hi, yes that is a legitimate concern. There is a hierarchy of key types to make this operation safer. For instance, you can provision client keys and grant them read only access to certain classes and indexes. Also you can use an authentication system to provision session keys for users and other instance-level access control principles.

The browser and the server client are the same. If you are curious, [here is a video of a meetup where I describe an app that runs serverless Lambda functions using instance level permissions.](https://fauna.com/blog/developing-serverless-authentication-and-persistence)

And here is preview code of an [example application I'm working on that allows user signup from the browser with no 3rd party runtime code.](https://github.com/fauna/todomvc-fauna/tree/direct-client-passwords)

Serving single page applications is just one of the FaunaDB use cases. Typical server side use cases will use server keys. See [more about FaunaDB access control here](https://fauna.com/documentation/security).
